dev:
  vars:
    ansible_user: test
  children:
    webserver:
      hosts:
        ubuntu-01:
          ansible_host: IP
          # ansible_user: nazwa_uzytkownika
        ubuntu-02:
          ansible_host: IP
          # ansible_user: nazwa_uzytkownika
    loadbalancer:
      # vars:
      #   ansible_user: ubuntu
      hosts:
        ubuntu-03:
          ansible_host: IP
          # ansible_user: nazwa_uzytkownika
local:
  children:
    my_pc:
      hosts:
        master_ansible:
          ansible_host: localhost
          ansible_connection: local